// This file is generated by the export-api-keys script
export const apiKeysExport = [
  {
    email: "app_admin@email.com",
    apiKeys: [
      {
        key: "key__0_app_admin@email.com00000000000000000000000000000000000000",
        status: "active",
        name: null,
        expiresAt: null,
        createdAt: "2026-02-05T21:59:17.214Z",
      },
    ],
  },
  {
    email: "expired.key@example.com",
    apiKeys: [
      {
        key: "expired_expired.key@example.com000000000000000000000000000000000",
        status: "expired",
        name: null,
        expiresAt: "2026-02-04T21:59:17.309Z",
        createdAt: "2026-02-05T21:59:17.307Z",
      },
    ],
  },
  {
    email: "high.balance@example.com",
    apiKeys: [
      {
        key: "key__0_high.balance@example.com000000000000000000000000000000000",
        status: "active",
        name: null,
        expiresAt: null,
        createdAt: "2026-02-05T21:59:17.284Z",
      },
    ],
  },
  {
    email: "multiple.keys@example.com",
    apiKeys: [
      {
        key: "key__0_multiple.keys@example.com00000000000000000000000000000000",
        status: "active",
        name: null,
        expiresAt: null,
        createdAt: "2026-02-05T21:59:17.289Z",
      },
      {
        key: "key__1_multiple.keys@example.com00000000000000000000000000000000",
        status: "active",
        name: null,
        expiresAt: null,
        createdAt: "2026-02-05T21:59:17.293Z",
      },
      {
        key: "key__2_multiple.keys@example.com00000000000000000000000000000000",
        status: "active",
        name: null,
        expiresAt: null,
        createdAt: "2026-02-05T21:59:17.296Z",
      },
      {
        key: "key__3_multiple.keys@example.com00000000000000000000000000000000",
        status: "active",
        name: null,
        expiresAt: null,
        createdAt: "2026-02-05T21:59:17.299Z",
      },
      {
        key: "key__4_multiple.keys@example.com00000000000000000000000000000000",
        status: "active",
        name: null,
        expiresAt: null,
        createdAt: "2026-02-05T21:59:17.302Z",
      },
    ],
  },
  {
    email: "standard.user@example.com",
    apiKeys: [
      {
        key: "key__0_standard.user@example.com00000000000000000000000000000000",
        status: "active",
        name: null,
        expiresAt: null,
        createdAt: "2026-02-05T21:59:17.270Z",
      },
    ],
  },
  {
    email: "vojta@czechibank.ostrava.digital",
    apiKeys: [
      {
        key: "key__0_vojta@czechibank.ostrava.digital0000000000000000000000000",
        status: "active",
        name: null,
        expiresAt: null,
        createdAt: "2026-02-05T21:59:17.260Z",
      },
    ],
  },
  {
    email: "zachrannas+brno@pejsekakocicka.cz",
    apiKeys: [
      {
        key: "key__0_zachrannas+brno@pejsekakocicka.cz000000000000000000000000",
        status: "active",
        name: null,
        expiresAt: null,
        createdAt: "2026-02-05T21:59:17.251Z",
      },
    ],
  },
  {
    email: "zachrannas+praha@pejsekakocicka.cz",
    apiKeys: [
      {
        key: "key__0_zachrannas+praha@pejsekakocicka.cz00000000000000000000000",
        status: "active",
        name: null,
        expiresAt: null,
        createdAt: "2026-02-05T21:59:17.240Z",
      },
    ],
  },
  {
    email: "zero.balance@example.com",
    apiKeys: [
      {
        key: "key__0_zero.balance@example.com000000000000000000000000000000000",
        status: "active",
        name: null,
        expiresAt: null,
        createdAt: "2026-02-05T21:59:17.277Z",
      },
    ],
  },
];
