import { PrismaClient } from "@prisma/client";
import * as fs from "fs";
import * as path from "path";

const prisma = new PrismaClient();

interface ApiKeyExport {
  email: string;
  apiKeys: Array<{
    key: string;
    status: "active" | "expired";
    name?: string | null;
    expiresAt?: string | null;
    createdAt: string;
  }>;
}

async function exportApiKeys() {
  console.log("[export-api-keys] Starting export...");

  try {
    // Get all users with their API keys
    const users = await prisma.user.findMany({
      include: {
        apikeys: true,
      },
      orderBy: {
        email: "asc",
      },
    });

    console.log(`[export-api-keys] Found ${users.length} users`);

    const exportData: ApiKeyExport[] = [];

    for (const user of users) {
      const apiKeys = user.apikeys.map((apiKey) => {
        const now = new Date();
        const expiresAt = apiKey.expiresAt ? new Date(apiKey.expiresAt) : null;
        const isExpired = expiresAt ? expiresAt < now : false;
        const isDisabled = apiKey.enabled === false;

        // Key is expired if it has an expiration date in the past, or if it's disabled
        const status: "active" | "expired" = isExpired || isDisabled ? "expired" : "active";

        return {
          key: apiKey.key,
          status,
          name: apiKey.name,
          expiresAt: apiKey.expiresAt?.toISOString() || null,
          createdAt: apiKey.createdAt.toISOString(),
        };
      });

      if (apiKeys.length > 0) {
        exportData.push({
          email: user.email,
          apiKeys,
        });
      }
    }

    // Create export directory if it doesn't exist
    const exportDir = path.join(process.cwd(), "scripts/seed-helpers");
    if (!fs.existsSync(exportDir)) {
      fs.mkdirSync(exportDir, { recursive: true });
    }

    // Write to JSON file
    const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
    const filename = `generated-api-keys-export.ts`;
    const filepath = path.join(exportDir, filename);

    fs.writeFileSync(
      filepath,
      `// This file is generated by the export-api-keys script\nexport const apiKeysExport = ${JSON.stringify(exportData, null, 2)};`,
      "utf-8",
    );

    console.log(`[export-api-keys] Export completed successfully!`);
    console.log(`[export-api-keys] Exported ${exportData.length} users with API keys`);
    console.log(`[export-api-keys] File saved to: ${filepath}`);

    // Also create a summary
    const totalKeys = exportData.reduce((sum, user) => sum + user.apiKeys.length, 0);
    const activeKeys = exportData.reduce(
      (sum, user) => sum + user.apiKeys.filter((k) => k.status === "active").length,
      0,
    );
    const expiredKeys = totalKeys - activeKeys;

    console.log(`[export-api-keys] Summary:`);
    console.log(`[export-api-keys]   - Total users: ${exportData.length}`);
    console.log(`[export-api-keys]   - Total API keys: ${totalKeys}`);
    console.log(`[export-api-keys]   - Active keys: ${activeKeys}`);
    console.log(`[export-api-keys]   - Expired keys: ${expiredKeys}`);

    return exportData;
  } catch (error) {
    console.error("[export-api-keys] Error exporting API keys:", error);
    throw error;
  }
}

async function main() {
  console.log("[export-api-keys] Starting API keys export script...");
  await prisma.$connect();

  try {
    await exportApiKeys();
  } catch (error) {
    console.error("[export-api-keys] Fatal error:", error);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
    console.log("[export-api-keys] Script finished");
    process.exit(0);
  }
}

main();
